### PR TITLE
ci(linter): Added style auto format and eslint test before git commit

### PR DESCRIPTION
**Pull request by OwenTruong**
#15 

Added eslint test when you run git commit. Also made it so that prettier will automatically format your code when you run git commit.

- clientside lint test
- clientside style test

### CODE REVIEW

**Comment by OwenTruong** [comment]
A potential concern is a different package-lock.json. 

I had to delete package-lock.json once when I was setting it up because lint-staged was not happy with it.

**Comment by miguel-merlin** [comment]
I checked other repositories that have the client and the server in the same repository, and I didn't see any issues with having multiple ```package-lock.json```. When you run ```npm rum``` npm will take the ```package.json``` in the same directory.  I don't think we will have any issues.

**Review by miguel-merlin — APPROVED** [review]

**Comment by OwenTruong** [comment]
> I checked other repositories that have the client and the server in the same repository, and I didn't see any issues with having multiple `package-lock.json`. When you run `npm rum` npm will take the `package.json` in the same directory. I don't think we will have any issues.

Not sure what you mean specifically, but multiple package-lock.json is fine. There should be one package-lock.json for every package.json that has dependencies. The problem was that the client/package-lock.json wasn't happy with the lint-staged dependency installed in client/package.json

**Comment by OwenTruong** [comment]
Merge request will be closed until prettier and eslint test is reconfigured for NextJS

**Pull request closed without merging**
