### PR TITLE
docs: Added laddhasuneedhi to contributors

### PR DESCRIPTION
**Pull request by laddhasuneedhi**

### CODE REVIEW

**Review by ericzty — APPROVED** [review]
lgtm, also tagging in #1

**Comment by ericzty** [comment]
oh, please also follow https://www.conventionalcommits.org/en/v1.0.0/ next time.
if you'd like, you can edit the commit message, that'd be even better.

**Review by ericzty — APPROVED** [review]

**Comment by miguel-merlin** [comment]
Also, for future reference. It is good practice to follow this convention for naming your branches. https://dev.to/varbsan/a-simplified-convention-for-naming-branches-and-commits-in-git-il4

**Review by miguel-merlin — APPROVED** [review]

**Review by miguel-merlin — APPROVED** [review]

**Comment by laddhasuneedhi** [comment]
Can I merge?

**Pull request merged**
