### PR TITLE
feat(docs): added name to CONTRIBUTORS.MD

### PR DESCRIPTION
**Pull request by Arnavpmr**
#1

### CODE REVIEW

**Review by ericzty — APPROVED** [review]
lgtm, in the future please use https://www.conventionalcommits.org/en/v1.0.0/ (for commit messages too), but we'll just rename the commit when we merge this.
nice work.

**Comment by Arnavpmr** [comment]
> lgtm, in the future please use https://www.conventionalcommits.org/en/v1.0.0/ (for commit messages too), but we'll just rename the commit when we merge this. nice work.

I will be sure to read through the docs tommorow!

**Comment by ericzty** [comment]
Please do not merge the PR without another developer (that's not a team lead) reviewing it.

**Comment by ericzty** [comment]
please remake the PR.

**Pull request merged**
