### PR TITLE
docs: Added simerm to Contributors file

### PR DESCRIPTION
**Pull request by simerm**

### CODE REVIEW

**Comment by ericzty** [comment]
please link the issue in the PR
please provide a description in the PR
please follow conventional commits

**Comment by simerm** [comment]
#1 
added "Simerjeet Mudhar" as contributor name to file

**Comment by ericzty** [comment]
I suppose I'll rename the commit when I merge this.
Please follow conventional commits in the future...

**Review by ericzty — APPROVED** [review]

**Comment by miguel-merlin** [comment]
Please follow, https://www.conventionalcommits.org/en/v1.0.0/

**Review by miguel-merlin — APPROVED** [review]
Approved!

**Pull request merged**
